Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -1,4 +1,4 @@
-name: Android CI
+name: Java Bindings CI
 
 on: [push, pull_request]
 
@@ -10,33 +10,36 @@ jobs:
     - name: Checkout Code
       uses: actions/checkout@v4
 
-    - name: Set up JDK 8
+    - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
-        java-version: '8'
+        java-version: '11'
         distribution: 'temurin'
 
-    - name: Grant execute permission for gradlew
-      run: chmod +x ./gradlew
+    - name: Compile and Run Tests
+      run: |
+        JNA=/usr/share/java/jna.jar
 
-    - name: Cache Gradle packages
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.gradle/caches
-          ~/.gradle/wrapper
-        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-        restore-keys: |
-          ${{ runner.os }}-gradle-
+        if [ ! -f ${JNA} ]; then
+          if [ ! -f /usr/share/java/jna/jna.jar ]; then
+            echo "*** Unable to find jna.jar *** ";
+            exit 1;
+          else
+            JNA=/usr/share/java/jna/jna.jar;
+          fi
+        fi
 
-    - name: Build Debug APK
-      run: ./gradlew assembleDebug
-
-    - name: Run tests
-      run: ./gradlew test
-
-    - name: Upload Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: apk
-        path: app/build/outputs/apk/debug/*.apk
+        case "\$1" in
+          "") java -classpath ${JNA}:. TestBasic ;;
+          "testbasic") java -classpath ${JNA}:. TestBasic ;;
+          "arm") java -classpath ${JNA}:. TestArm ;;
+          "arm64") java -classpath ${JNA}:. TestArm64 ;;
+          "mips") java -classpath ${JNA}:. TestMips ;;
+          "x86") java -classpath ${JNA}:. TestX86 ;;
+          "xcore") java -classpath ${JNA}:. TestXcore; ;;
+          "ppc") java -classpath ${JNA}:. TestPpc ;;
+          "sparc") java -classpath ${JNA}:. TestSparc ;;
+          "systemz") java -classpath ${JNA}:. TestSystemz ;;
+          "m680x") java -classpath ${JNA}:. TestM680x ;;
+          * ) echo "Usage: ./run.sh [arm|arm64|m680x|mips|ppc|sparc|systemz|x86]"; exit 1;;
+        esac
